---
new_page_extension: md
auto_deploy: false
admin_path: "/_admin"
webhook_url: 
collections:
- type: directory
  path: _posts
  label: Posts
  create: all
- type: directory
  path: _pages
  label: Pages
  create: all
- type: directory
  path: _people
  label: People
  create: all
- type: directory
  path: ''
  label: Pages
  create: none
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
