---
new_page_extension: md
auto_deploy: false
admin_path: "/admin"
webhook_url: 
sections:
- type: jekyll-posts
  path: _posts
  label: Posts
  create: all
  match: "**/*"
- type: directory
  path: _pages
  label: Pages
  create: all
  match: "**/*"
- type: directory
  path: _people
  label: Pages
  create: all
  match: "**/*"
- type: jekyll-pages
  path: ''
  label: Pages
  create: none
  match: "**/*"
- type: directory
  label: Jekyll Pages
  path: _jerk_face
  match: "*"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
