---
new_page_extension: md
auto_deploy: false
admin_path: "/edit"
webhook_url: 
sections:
- type: document
  path: README.md
  label: README
  read_only: true
- type: jekyll-posts
  label: Posts
  create: all
- type: directory
  path: _people
  label: People
  create: all
  match: "**/*"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
