---
new_page_extension: md
auto_deploy: false
admin_path: "/admin"
webhook_url: 
sections:
- type: directory
  path: one
  label: One
  create: all
  match: "**/*"
- type: directory
  path: four
  label: Four
  create: all
  match: "**/*"
- type: directory
  path: two
  label: Two
  create: all
  match: "**/*"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
