---
new_page_extension: md
auto_deploy: false
admin_path: "/admin-3"
webhook_url: 
sections:
- type: directory
  path: _people
  label: People
  create: all
  match: "**/*"
  exclude: 
- type: directory
  path: _pages
  label: Pages
  create: all
  match: "**/*"
  exclude: 
- type: jekyll-posts
  label: Posts
  create: all
- type: directory
  path: _custom/bikes
  label: Bikes
  create: all
  match: "*"
  exclude: 
- type: directory
  path: _custom/cars
  label: French Cars
  create: all
  match: "*.fr.md"
  exclude: 
  new_doc_ext: fr.md
- type: directory
  path: _custom/cars
  label: English Cars
  create: all
  match: "*.en.md"
  exclude: 
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
