---
new_page_extension: md
auto_deploy: false
admin_path: "/admin-3"
webhook_url: 
collections:
- type: directory
  path: _people
  label: People
  create: all
  match: "**/*"
- type: directory
  path: _pages
  label: Pages
  create: all
  match: "**/*"
- type: jekyll-posts
  path: _posts
  label: Posts
  create: all
- type: directory
  path: _custom/bikes
  label: Bikes
  match: "*"
- type: directory
  path: _custom/cars
  label: French Cars
  match: "*.fr.md"
  new_doc_ext: ".fr.md"
- type: directory
  path: _custom/cars
  label: English Cars
  match: "*.en.md"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
