---
new_page_extension: md
auto_deploy: false
admin_path: "/admax"
webhook_url: 
sections:
- type: directory
  path: _my_data
  label: Datafiles
  create: all
  match: "**/*"
- type: jekyll-posts
  label: Posts
  create: all
  templates:
  - example
- type: directory
  path: _pages
  label: Pages
  create: all
  match: "**/*"
- type: directory
  path: _people
  label: People
  create: all
  match: "**/*"
- type: jekyll-pages
  label: Pages
  create: none
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
