---
new_page_extension: md
auto_deploy: false
admin_path: "/admin-cake-1"
webhook_url: ''
collections:
- path: _people
  label: People
  create: all
  default_front_matter_template: people
  templates:
  - people
- path: _pages
  label: Pages
  create: all
  default_front_matter_template: example
  templates: 
  - people
- path: _posts
  label: Posts
  create: all
- path: ''
  label: Pages
  create: all
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
