---
new_page_extension: md
auto_deploy: false
admin_path: "/admin"
webhook_url: 
collections:
- path: _custom/cars/*
  label: Custom Cars
  create: documents
- path: _pages/**/*
  label: Pages
  create: all
- path: "{_posts,_drafts}/**/*"
  label: Posts
  create: all
- path: _people/*
  label: People
  create: documents
  templates:
  - example
- path: _people/sub-people/*
  label: Sub-People
  create: documents
  templates:
  - example
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
