---
new_page_extension: md
auto_deploy: false
admin_path: "/admin"
webhook_url: 
sections:
- type: document
  path: _my_data/colors.yml
  label: Colors
- type: jekyll-posts
  label: Posts
  create: all
  templates:
  - post
- type: directory
  path: _pages
  label: Pages
  create: all
  match: "**/*"
- type: directory
  path: _people
  label: People
  create: all
  match: "**/*"
  exclude: "{one,two}.md"
- type: jekyll-pages
  label: Pages
  create: none
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
